dependency check

diff --git a/bank/Dockerfile b/bank/Dockerfile
--- a/bank/Dockerfile
+++ b/bank/Dockerfile
@@ -1,10 +1,37 @@
 FROM ubuntu:latest
 
 # Install any necessary dependencies or packages
-#RUN apt-get update && apt-get install -y \
-    # Package1 \
-    # Package2 \
-    # ...
+RUN apt-get update && apt-get install -y \
+    zip  \
+    unzip  \
+    build-essential  \
+    pkg-config  \
+    libpthread-stubs0-dev \
+    libxml2  \
+    gcc  \
+    cmake  \
+    wget  \
+    msmtp \
+
+# install vcpkg
+RUN  wget -qO vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz \
+      sudo mkdir /opt/vcpkg \
+      sudo tar xf vcpkg.tar.gz --strip-components=1 -C /opt/vcpkg \
+      sudo /opt/vcpkg/bootstrap-vcpkg.sh \
+      sudo ln -s /opt/vcpkg/vcpkg /usr/local/bin/vcpkg
+
+
+# VERIFY VCPKG
+
+RUN  echo "Verifying dependencies" \
+  # check if vcpkg is installed
+  if ! command -v /usr/local/bin/vcpkg &> /dev/null \
+  then \
+      echo "vcpkg could not be found" \
+      exit \
+  fi \
+  echo "vcpkg ok" \
+
 RUN ls -la
 
 # Set the working directory to /app
@@ -15,10 +42,7 @@ COPY . /bankApp
 
 RUN ls -la
 
-# Run your scripts or commands inside the container
-RUN chmod +x scripts/install_dependencies.sh  # Make the scripts executable
-RUN scripts/install_dependencies.sh  # Replace with your script/command
-#RUN ./script2.sh  # Replace with your script/command
+
 
 # Define any additional configuration or settings
 EXPOSE 80
